FROM openjdk:17-alpine
ARG JAR_FILE=target/payment-service-app.jar
COPY ${JAR_FILE} payment_docker_app.jar
ENTRYPOINT ["java", "-jar", "/payment_docker_app.jar"]
12345679890--\][poiuytrewq	ASDFFGHJKKL;//?>>.,,,,mMMNNNBBVCXXZZA 897745561223+ .